// Calm, true facts about flying. `only` limits a fact to routes it's about.
const FACT_CATS = ['Turbulence', 'How planes fly', 'Pilots & crew', 'Safety', 'History', 'Fun facts', 'Your route'];
const FACTS = [
  // Turbulence
  { cat: 'Turbulence', text: 'Turbulence is just moving air, like waves under a boat. The plane rides over it. It isn\'t fighting it.' },
  { cat: 'Turbulence', text: 'Airliner wings are tested by bending them far beyond anything turbulence can do. They flex on purpose, like a diving board.' },
  { cat: 'Turbulence', text: 'What feels like a big drop is usually only a few metres. Your body exaggerates it.' },
  { cat: 'Turbulence', text: 'Pilots hear about bumps from planes ahead and change height to find smoother air. They\'re probably doing it right now.' },
  { cat: 'Turbulence', text: 'The seatbelt sign means "stay seated so you don\'t bump your head". It doesn\'t mean danger.' },
  { cat: 'Turbulence', text: 'Most patches of turbulence last only a few minutes.' },
  { cat: 'Turbulence', text: 'To pilots, turbulence is like a bumpy road. It\'s about comfort, not safety.' },
  { cat: 'Turbulence', text: 'Climbing and descending through cloud is where most bumps live. The air above the clouds is usually much calmer.' },
  { cat: 'Turbulence', text: 'If the crew are still walking around, it\'s mild. If they sit down, that\'s only so they stay steady, same as you.' },
  { cat: 'Turbulence', text: 'Your seatbelt, done up snugly, is all you need. Then you\'re in the safest place on the plane.' },
  { cat: 'Turbulence', text: 'Airliners are built to be stable. Bumps nudge them, and they naturally settle right back to straight and level.' },
  { cat: 'Turbulence', text: 'Bumps feel a bit bigger at the back of the plane. That changes nothing about how safe you are.' },
  { cat: 'Turbulence', text: 'In bumpy air, pilots often slow to a special "turbulence speed" that makes the ride gentler.' },
  { cat: 'Turbulence', text: 'A weather radar in the nose of the plane shows storms ahead, and pilots steer well around them.' },
  { cat: 'Turbulence', text: 'Hot days make warm air rise off the ground like bubbles in a pot. That\'s why it\'s bumpier low down in the tropics and smoother higher up.' },
  { cat: 'Turbulence', text: 'Air flowing over mountains makes gentle waves, like water flowing over rocks. That\'s why hilly airports can have a bouncy approach.' },
  { cat: 'Turbulence', text: 'Sometimes there are bumps under a clear blue sky. That\'s "clear-air turbulence" near fast winds high up. It\'s harmless when you\'re buckled in.' },
  { cat: 'Turbulence', text: 'Every bump you feel is one less between you and {to}.' },

  // How planes fly
  { cat: 'How planes fly', text: 'Wings push air down, and the air pushes the wings up. At cruise, the wings hold up the whole plane with ease.' },
  { cat: 'How planes fly', text: 'Jets are great gliders. From cruising height they can glide well over 100 km. Engines are for going forward, not for staying up.' },
  { cat: 'How planes fly', text: 'Twin-engine airliners are certified to fly for hours on just one engine.' },
  { cat: 'How planes fly', text: 'Most of the fuel is stored inside the wings. On long flights the plane gets many tonnes lighter as it burns it.' },
  { cat: 'How planes fly', text: 'Planes cruise around 10–12 km up, above most weather, where the air is thin and smooth.' },
  { cat: 'How planes fly', text: 'The cabin is pressurised to feel like being on a hill about 2,000 m high. That\'s why snack bags puff up.' },
  { cat: 'How planes fly', text: 'Planes take off into the wind because it gives the wings extra lift at a lower speed.' },
  { cat: 'How planes fly', text: 'The upturned tips at the end of the wings are called winglets. They cut drag and save fuel.' },
  { cat: 'How planes fly', text: 'Flaps slide out from the back of the wings for takeoff and landing. They make the wing bigger so the plane can fly slowly and safely.' },
  { cat: 'How planes fly', text: 'An airliner lifts off at about 250–290 km/h and cruises at about 850–900 km/h.' },
  { cat: 'How planes fly', text: 'The tail keeps the plane pointing straight, like the feathers on an arrow.' },
  { cat: 'How planes fly', text: 'The white trails behind planes are clouds the plane makes. Water vapour from the engines freezes into ice crystals.' },
  { cat: 'How planes fly', text: 'On a map, flight paths look curved. On a round Earth that curve is actually the shortest way.' },

  // Pilots & crew
  { cat: 'Pilots & crew', text: 'There are always at least two pilots, and each one can fly the plane alone.' },
  { cat: 'Pilots & crew', text: 'Pilots often eat different meals from each other, just so they\'re never both unwell at once.' },
  { cat: 'Pilots & crew', text: 'Pilots train in full-motion simulators every year. Anything unusual is something they\'ve practised many times.' },
  { cat: 'Pilots & crew', text: 'Before every flight, the plane gets a walk-around check. There\'s a checklist for almost everything.' },
  { cat: 'Pilots & crew', text: 'Air traffic controllers watch every plane on radar and keep them kilometres apart.' },
  { cat: 'Pilots & crew', text: 'Autopilot flies most of the cruise while the pilots watch the weather and plan ahead.' },
  { cat: 'Pilots & crew', text: 'Many airliners can even land themselves in thick fog. It\'s called autoland.' },
  { cat: 'Pilots & crew', text: 'Flight attendants are safety experts first. Serving drinks is the second part of their job.' },
  { cat: 'Pilots & crew', text: 'The "ding" sounds in the cabin are usually the crew calling each other, or the seatbelt sign changing. They aren\'t alarms.' },
  { cat: 'Pilots & crew', text: 'Pilots and controllers all over the world talk to each other in English on the radio.' },

  // Safety
  { cat: 'Safety', text: 'Flying is one of the safest ways to travel. The drive to the airport carries more risk than the flight.' },
  { cat: 'Safety', text: 'Planes have backups for their backups. Electrics, hydraulics and computers usually come in twos or threes.' },
  { cat: 'Safety', text: 'An airliner is hit by lightning about once a year on average. It\'s built to let the lightning pass harmlessly around the outside.' },
  { cat: 'Safety', text: 'Planes are serviced on a strict schedule, and parts are replaced long before they wear out.' },
  { cat: 'Safety', text: 'A "go-around" is when a plane skips a landing and climbs away to try again. It\'s a normal safety choice, not an emergency.' },
  { cat: 'Safety', text: 'In a crosswind, planes land pointing a little sideways. It\'s called crabbing and it\'s a normal technique.' },
  { cat: 'Safety', text: 'The doors can\'t be opened in flight. Air pressure inside pushes them shut like a plug in a bath.' },
  { cat: 'Safety', text: 'Cabin lights dim for landing so your eyes are already used to the light outside. It\'s routine.' },
  { cat: 'Safety', text: 'Window shades are opened for takeoff and landing so the crew can see outside. It\'s routine.' },
  { cat: 'Safety', text: 'The tiny hole in the window lets the outer pane take the pressure while the inner pane stays relaxed.' },

  // History of flight
  { cat: 'History', text: 'The Wright brothers made the first powered flight on 17 December 1903. It lasted 12 seconds and covered about 37 m, less than the wingspan of a modern airliner.' },
  { cat: 'History', text: 'The first scheduled airline flight took off on 1 January 1914 in Florida. It carried one passenger 23 minutes across Tampa Bay.' },
  { cat: 'History', text: 'In 1927 Charles Lindbergh made the first solo nonstop flight across the Atlantic. It took him about 33½ hours. Today it takes around 7.' },
  { cat: 'History', text: 'In 1932 Amelia Earhart became the first woman to fly solo across the Atlantic.' },
  { cat: 'History', text: 'In 1930 Ellen Church became the first flight attendant. Early flight attendants had to be trained nurses.' },
  { cat: 'History', text: 'The jet engine was invented separately in the 1930s by Frank Whittle in England and Hans von Ohain in Germany.' },
  { cat: 'History', text: 'The first jet airliner, the de Havilland Comet, started carrying passengers in 1952.' },
  { cat: 'History', text: 'By the late 1950s, more people were crossing the Atlantic by plane than by ship.' },
  { cat: 'History', text: 'The flight recorder ("black box") was invented in the 1950s by David Warren, an Australian scientist.' },
  { cat: 'History', text: 'The Boeing 747 "Jumbo Jet" carried its first passengers in 1970 and made flying affordable for millions of people.' },
  { cat: 'History', text: 'Concorde flew from London to New York in about 3½ hours at twice the speed of sound. It retired in 2003.' },
  { cat: 'History', text: 'The Airbus A380, the biggest passenger plane ever built, entered service in 2007 with Singapore Airlines.' },
  { cat: 'History', text: 'In-flight movies began in the 1920s, when films were shown on early airliners.' },
  { cat: 'History', only: /chiang mai|bangkok|thai|phuket/i, text: 'The first aeroplane flight in Thailand was a demonstration in Bangkok in 1911.' },
  { cat: 'History', only: /chiang mai|bangkok|thai|phuket/i, text: 'Bangkok\'s Don Mueang airport opened in 1914, making it one of the oldest airports in Asia.' },

  // Fun facts
  { cat: 'Fun facts', text: 'Thousands of planes are flying right now, all around the world.' },
  { cat: 'Fun facts', text: 'A Boeing 747 is made of about 6 million parts.' },
  { cat: 'Fun facts', text: 'The "black box" flight recorder is actually bright orange so it\'s easy to spot.' },
  { cat: 'Fun facts', text: 'Your sense of taste gets weaker up here. Dry air and low pressure dull sweet and salty flavours, which is why plane food is seasoned more.' },
  { cat: 'Fun facts', text: 'Tomato juice tastes better on planes. With taste dulled, its savoury flavour stands out more.' },
  { cat: 'Fun facts', text: 'The shortest scheduled flight in the world, in Scotland\'s Orkney islands, takes under two minutes.' },
  { cat: 'Fun facts', text: 'Plane toilet doors have a hidden latch on the outside so crew can open them if needed.' },
  { cat: 'Fun facts', text: 'Cabin air is very dry, drier than most deserts. Sipping water helps you feel fresh.' },
  { cat: 'Fun facts', text: 'Planes are usually painted white because it reflects sunlight, stays cooler and shows cracks easily during checks.' },

  // Route specific
  { cat: 'Your route', only: /chiang mai|bangkok/i, text: 'Bangkok to Chiang Mai is one of Thailand\'s busiest routes. Crews fly it many times a day and know every bump.' },
  { cat: 'Your route', only: /chiang mai/i, text: 'Chiang Mai airport sits next to Doi Suthep, a mountain about 1,676 m tall with a golden temple near the top.' },
  { cat: 'Your route', only: /chiang mai|bangkok/i, text: 'Airport codes: BKK is Suvarnabhumi, DMK is Don Mueang and CNX is Chiang Mai.' },
  { cat: 'Your route', only: /bangkok/i, text: 'Suvarnabhumi airport in Bangkok has one of the tallest control towers in the world, about 132 m high.' },
  { cat: 'Your route', only: /chiang mai|bangkok|thai/i, text: 'Thailand\'s national airline, Thai Airways, started flying in 1960.' },
];
